// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Ym7EuvlbDxiuDQJlRVeUqVT5-L2jXV8',
    appId: '1:682714871414:web:c1061e7675f2d42b761157',
    messagingSenderId: '682714871414',
    projectId: 'class-ping-66823',
    authDomain: 'class-ping-66823.firebaseapp.com',
    storageBucket: 'class-ping-66823.firebasestorage.app',
    measurementId: 'G-GK0NJ53Z70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByQBebIblmO0_jA46ezsM_F1TV6KGdUNw',
    appId: '1:682714871414:android:d339c7e9ce93e975761157',
    messagingSenderId: '682714871414',
    projectId: 'class-ping-66823',
    storageBucket: 'class-ping-66823.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaQtzZgzkhODsqqnrfi48sTsZv6uWTklM',
    appId: '1:682714871414:ios:1ca986ad1eb01882761157',
    messagingSenderId: '682714871414',
    projectId: 'class-ping-66823',
    storageBucket: 'class-ping-66823.firebasestorage.app',
    iosBundleId: 'com.classping.classping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaQtzZgzkhODsqqnrfi48sTsZv6uWTklM',
    appId: '1:682714871414:ios:1ca986ad1eb01882761157',
    messagingSenderId: '682714871414',
    projectId: 'class-ping-66823',
    storageBucket: 'class-ping-66823.firebasestorage.app',
    iosBundleId: 'com.classping.classping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-Ym7EuvlbDxiuDQJlRVeUqVT5-L2jXV8',
    appId: '1:682714871414:web:9991fa16782029fa761157',
    messagingSenderId: '682714871414',
    projectId: 'class-ping-66823',
    authDomain: 'class-ping-66823.firebaseapp.com',
    storageBucket: 'class-ping-66823.firebasestorage.app',
    measurementId: 'G-45RCB038W2',
  );
}
